### PR TITLE
WIP: Minor changes regarding error handlng and requirements

### PR DESCRIPTION
**Pull request by FelixKleineBoesing**
fixes issue #1

### CODE REVIEW

**Comment by FelixKleineBoesing** [comment]
Hey Alex, 
thanks for the library. Let me add some things please :)

**Comment by alex9smith** [comment]
Sorry, I didn't get a notification that you'd opened this PR! This all looks great.

I've made a couple of changes since you opened it. If you can resolve the conflicts I'd be happy to merge

**Comment by alex9smith** [comment]
I merged this manually because I wanted some of the features. Thanks again!

**Comment by FelixKleineBoesing** [comment]
Yeah, sorry. I hadn´t the time yet to resolve the conflicts, sry :)

**Pull request merged**
